window.ENV = {
  WEBSITE_TITLE: 'example',
  EMAIL_CONTACT: 'example@gmail.com',
  API_URL: 'http://localhost',
  GOOGLE_CAPTCHA_ID: 'GOOGLE_CAPTCHA_ID',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  FACEBOOK_CLIENT_ID: 'FACEBOOK_CLIENT_ID',
  STRIPE_API: 'STRIPE_API',
  ANALYTICS: 'ANALYTICS',
};
